### ISSUE TITLE
Help me please!

### ISSUE THREAD

**Issue by 439bananas** [jacob-g/wikimonitor#1]
Hello. I've made a script and I need help starting it. Can you help please?

```
```

**Comment by jacob-g** [comment]
You need to run it on a computer or server that has PHP set up. Once you have that, navigate to the directory where the script is stored in a terminal session, and type in the following:
`php -f main.php`

**Comment by 439bananas** [comment]
Oh... my script uses JS.

**Comment by jacob-g** [comment]
You can only run JS within a webpage, you can't run it as a command line script. Also, please keep issues for this project related to the project itself.

**Comment by 439bananas** [comment]
oh...

**Comment by 439bananas** [comment]
I got it. Don't you run a JS bot in inspect element?

**Comment by jacob-g** [comment]
Yeah, you can do that with a JS bot.

**Comment by 439bananas** [comment]
Got ya :)

**Comment by joker314** [comment]
Or you might want to use Node.js
