### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by kj7rrv** [jacob-g/wikimonitor#12]
I'm interested in using this for another wiki and possibly making changes, but there is no license. Is it all rights reserved?

**Comment by R4356th** [comment]
@jacob-g, this is my question, too. Can it be used at @InternationalScratchWiki -s?

**Comment by jacob-g** [comment]
Feel free to use it and make modifications, please just give me some sort of credit. If you have any particularly interesting modifications, I'd love to see them!

**Comment by R4356th** [comment]
> Feel free to use it and make modifications, please just give me some sort of credit. If you have any particularly interesting modifications, I'd love to see them!

Thank you, @jacob-g!

**Comment by kj7rrv** [comment]
Will you please put an actual license though? it's very helpful for people
who find the repo. Apache 2.0 or MIT should do what you said, but IANAL.

**Comment by jacob-g** [comment]
License has been added (Apache). Just one thing to note is that if you have any problems, I can't guarantee I'll be able to help you.

**Comment by kj7rrv** [comment]
Thank you!
